apiVersion: v2
appVersion: 3.3.2
engine: gotpl
home: https://github.com/observiq/application-helm-charts/tree/main/charts/apache-hadoop
keywords:
  - community
  - forum
maintainers:
  - name: observIQ
name: hadoop
sources:
  - https://hadoop.apache.org/
version: 1.0.1
